export const GET_PERSON_INFO_REQUEST = 'GET_PERSON_INFO_REQUEST';
export const GET_PERSON_INFO_SUCCESS = 'GET_PERSON_INFO_SUCCESS';
export const GET_PERSON_INFO_FAILURE = 'GET_PERSON_INFO_FAILURE';

export const GET_AFFORDABILITY_RANGES_REQUEST = 'GET_AFFORDABILITY_RANGES_REQUEST';
export const GET_AFFORDABILITY_RANGES_SUCCESS = 'GET_AFFORDABILITY_RANGES_SUCCESS';
export const GET_AFFORDABILITY_RANGES_FAILURE = 'GET_AFFORDABILITY_RANGES_FAILURE';

export const GET_EXPOSURE_VALUES_REQUEST = 'GET_EXPOSURE_VALUES_REQUEST';
export const GET_EXPOSURE_VALUES_SUCCESS = 'GET_EXPOSURE_VALUES_SUCCESS';
export const GET_EXPOSURE_VALUES_FAILURE = 'GET_EXPOSURE_VALUES_FAILURE';
